update: dependency checks

diff --git a/.scripts/screenshot b/.scripts/screenshot
--- a/.scripts/screenshot
+++ b/.scripts/screenshot
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# Checking and installing dependencies
+dependencies=("slurp" "grim" "convert" "swappy")
+for dep in "${dependencies[@]}"; do
+    command -v "$dep" &> /dev/null || { echo "$dep not found, please install it."; exit 1; }
+done
+
 # Capture screenshot
 screenshot="$(slurp)"
 
